platform :ios, '10.0'
use_modular_headers!
use_frameworks!
inhibit_all_warnings!


target 'SafeYou' do
    
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD'
  pod 'SDWebImage'    #, '~>3.8'
  pod 'DZNEmptyDataSet'
  pod 'GoogleMaps'
  pod 'Socket.IO-Client-Swift' , '~> 15.2.0'
  pod 'TTTAttributedLabel'
  pod 'UITextView+Placeholder'
  pod 'NYTPhotoViewer'
  pod 'Lokalise'
  pod 'Pushy', '1.0.43'
  pod 'Branch'

end
